/*
 * adventures_with_ip.c
 *
 * Main source file. Contains main() and menu() functions.
 */
#include "adventures_with_ip.h"


/* ---------------------------------------------------------------------------- *
 * 									main()										*
 * ---------------------------------------------------------------------------- *
 * Runs all initial setup functions to initialise the audio codec and IP
 * peripherals, before calling the interactive menu system.
 * ---------------------------------------------------------------------------- */
int main(void)
{
	xil_printf("Entering Main\r\n");
	//Configure the IIC data structure
	IicConfig(XPAR_XIICPS_0_DEVICE_ID);

	//Configure the Audio Codec's PLL
	AudioPllConfig();

	//Configure the Line in and Line out ports.
	//Call LineInLineOutConfig() for a configuration that
	//enables the HP jack too.
	AudioConfigureJacks();

	xil_printf("ADAU1761 configured\n\r");

	/* Initialise GPIO and NCO peripherals */
	gpio_init();
	//nco_init(&Nco);

	xil_printf("GPIO and NCO peripheral configured\r\n");

	/* Display interactive menu interface via terminal */
	xil_printf("STARTUP AUDIO PLAYINGGGGGGGGGGGGGGGGGGGGGGGGGG\n\r");

	while(1){
		for (int i = 0; i < 278784; i++)
		{
			Xil_Out32(I2S_DATA_TX_L_REG, startupaudio[i][0]);
			Xil_Out32(I2S_DATA_TX_R_REG, startupaudio[i][1]);

			if (XUartPs_IsReceiveData(UART_BASEADDR)) {
				if (XUartPs_ReadReg(UART_BASEADDR, XUARTPS_FIFO_OFFSET) == 'q'){
					break;
				}
			}

			usleep(20);
		}
		xil_printf("STARTUP AUDIO ENDINGGGGGGGGGGGGGGGGGGGGGGGGGG\n\r");
	}
	//menu();
    return 1;
}

/* ---------------------------------------------------------------------------- *
 * 									menu()										*
 * ---------------------------------------------------------------------------- *
 * Presented at system startup. Allows the user to select between three
 * options by pressing certain keys on the keyboard:
 * 		's' - 	Audio loopback streaming
 * 		'n' - 	Tonal noise is generated by an NCO and added to the audio
 * 				being captured from the audio codec.
 * 		'f' - 	The audio + tonal noise is passed to an adaptive LMS noise
 * 				cancellation filter which will use the tonal noise estimate
 * 				to remove the noise from the audio.
 * 		'r' -	Record audio
 * 		'p' -	Playback recorded audio
 *
 * 	This menu is shown upon exiting from any of the above options.
 * ---------------------------------------------------------------------------- */
void menu(){

	u32 * left_audio_memory = malloc(sizeof(u32) * 240000); // 48,000 samples per second for 5 seconds
	u32 * right_audio_memory = malloc(sizeof(u32) * 240000); // 48,000 samples per second for 5 seconds

	u8 inp = 0x00;
	u32 CntrlRegister;

	/* Turn off all LEDs */
	Xil_Out32(LED_BASE, 0);

	CntrlRegister = XUartPs_ReadReg(UART_BASEADDR, XUARTPS_CR_OFFSET);

	XUartPs_WriteReg(UART_BASEADDR, XUARTPS_CR_OFFSET,
				  ((CntrlRegister & ~XUARTPS_CR_EN_DIS_MASK) |
				   XUARTPS_CR_TX_EN | XUARTPS_CR_RX_EN));



	// Wait for input from UART via the terminal
	while(1) {

		xil_printf("\r\n\r\n");
		xil_printf("Embedded LMS Filtering Demo\r\n");
		xil_printf("Enter 'r' to record and 'p' to playback.\nEnter '1' to playback fast and '2' to playback slowly\r\n");
		xil_printf("----------------------------------------\r\n");

		while (!XUartPs_IsReceiveData(UART_BASEADDR));
					inp = XUartPs_ReadReg(UART_BASEADDR, XUARTPS_FIFO_OFFSET);
		// Select function based on UART input
		switch(inp){
		case 's':
			xil_printf("STREAMING AUDIO\r\n");
			xil_printf("Press 'q' to return to the main menu\r\n");
			audio_stream();
			break;
		case 'n':
			xil_printf("ENTERING NOISE GENERATION OPERATION\r\n");
			xil_printf("Select step size via the DIP switches...\r\n\n");
			xil_printf("Press 'q' to return to the main menu\r\n");
			//tonal_noise();
			break;
		case 'f':
			xil_printf("ENTERING LMS FILTERING OPERATION\r\n");
			xil_printf("Press 'q' to return to the main menu\r\n");
			//lms_filter();
			break;
		case 'r':
			xil_printf("RECORDING AUDIO\r\n");
			xil_printf("Press 'q' to return to the main menu\r\n");
			record_audio(left_audio_memory, right_audio_memory);
			break;
		case 'p':
			xil_printf("PLAYING BACK RECORDING\r\n");
			xil_printf("Press 'q' to return to the main menu\r\n");
			playback_audio(left_audio_memory, right_audio_memory);
			break;
		case '1':
			xil_printf("FAST PLAY BACK\r\n");
			xil_printf("Press 'q' to return to the main menu\r\n");
			playback_audio_spedup(left_audio_memory, right_audio_memory);
			break;
		case '2':
			xil_printf("SLOW PLAY BACK\r\n");
			xil_printf("Press 'q' to return to the main menu\r\n");
			playback_audio_sloweddown(left_audio_memory, right_audio_memory);
			break;
		default:
			menu();
			break;
		} // switch
	}
} // menu()


