#ifndef PACMAN_DIES_AUDIO_H_
#define PACMAN_DIES_AUDIO_H_

#define PACMANDIESAUDIO_SAMPLE_SIZE 82944

signed long int pacmandiesaudio[PACMANDIESAUDIO_SAMPLE_SIZE][2];

#endif /* PACMAN_DIES_AUDIO_H_ */
